type: release
name: MyConfig
version: 0.1
description: Demo deployment configuration
ion: 0.0.1
apps:
  - name: hello
    description: Hello service
    version: 0.1
    processapp: [hello, ion.service.examples.hello_service, HelloService]
    config:
        some: "Hi"

  - name: hello1
    version: 0.1
    config:
        some: "Ho"
        service:
            name: hello

  - name: hello2
    version: 0.1
    config:
        some: "Hop"
        service:
            name: hello