# Example personal system configuration.
# Copy to parent directory and modify as needed. Do not add to git.

system:
  load_policy: False
  name: scion

server:
  amqp:
    # The normal container broker connection
    type: amqp_91
    host: localhost
    port: 5672
    username: guest
    password: guest
    vhost: /
    heartbeat: 30
  rabbit_manage:
    # REST access to RabbitMQ management plugin
    type: rabbit_mgmt
    host: localhost
    port: 15672
    username: guest
    password: guest

  postgresql:
    type: postgresql
    host: localhost
    port: 5432
    username: ion
    password:
    admin_username:             # If empty, defaults to current login username
    admin_password:
    default_database: postgres  # Postgres' internal database
    database: ion               # Database name for OOI Network (will be sysname prefixed)
    connection_pool_max: 5      # Number of connections for entire container

container:
  tracer:
    enabled: True
    max_entries: 100000
    log_trace: False
    log_filter: DB
    log_stack: False
    log_color: True

process:
  admin_ui:                  # Config for admin UI, started with --mx option
    web_server:
      port: 8080
