type: release
name: basic
version: 0.1
description: SciON basic services
ion: 2.0
apps:
  ##################################
  # CORE SERVICES
  # Bootstrap processes perform initializations
  ##################################

  - name: event_persister
    processapp: [event_persister, ion.process.event.event_persister, EventPersister]
    bootlevel: 1

  - name: bootstrapper1
    processapp: [bootstrapper1, ion.process.bootstrap.bootstrapper, Bootstrapper]
    bootlevel: 2
    config:
      bootstrap_plugins:
        - plugin: [ion.process.bootstrap.plugins.bootstrap_core, BootstrapCore]

  - name: resource_registry
    processapp: [resource_registry, ion.service.resource_registry_service, ResourceRegistryService]
    bootlevel: 5
    replicas: 1

  - name: system_management
    processapp: [system_management, ion.service.system_management_service, SystemManagementService]
    bootlevel: 5

  - name: directory
    processapp: [directory, ion.service.directory_service, DirectoryService]
    bootlevel: 8

  - name: identity_management
    processapp: [identity_management, ion.service.identity_management_service, IdentityManagementService]
    bootlevel: 8

  - name: policy_management
    processapp: [policy_management, ion.service.policy_management_service, PolicyManagementService]
    bootlevel: 8

  - name: exchange_management
    processapp: [exchange_management, ion.service.exchange_management_service, ExchangeManagementService]
    bootlevel: 8

  - name: org_management
    processapp: [org_management, ion.service.org_management_service, OrgManagementService]
    bootlevel: 8

  - name: bootstrapper2
    processapp: [bootstrapper2, ion.process.bootstrap.bootstrapper, Bootstrapper]
    bootlevel: 9
    config:
      bootstrap_plugins:
        - plugin: [ion.process.bootstrap.plugins.bootstrap_org, BootstrapOrg]
        - plugin: [ion.process.bootstrap.plugins.bootstrap_exchange, BootstrapExchange]

  ##################################
  # HIGHER LEVEL SERVICES
  ##################################

  - name: resource_management
    processapp: [resource_management, ion.service.resource_management_service, ResourceManagementService]
    bootlevel: 10

#  - name: process_management
#    processapp: [process_management, ion.service.process_management_service, ProcessManagementService]
#    bootlevel: 10

  # The bootstrap for loading policy should be the final bootstrap process.
  - name: policy_bootstrap
    processapp: [policy_bootstrap, ion.process.bootstrap.bootstrapper, Bootstrapper]
    bootlevel: 29
    config:
      bootstrap_plugins:
        - plugin: [ion.process.bootstrap.plugins.bootstrap_policy, BootstrapPolicy]

  ##################################
  # UI SERVER AND SERVICE GATEWAY
  ##################################

  - name: ui_server
    processapp: [ui_server, ion.process.ui.server, UIServer]
    bootlevel: 30
