type: release
name: scion_prod
version: 0.1
description: Scientific Observatory Network, production system start
ion: 2.0
apps:
  ##################################
  # CORE SERVICES
  # Bootstrap processes perform initializations
  ##################################

  - name: bootstrapper1
    processapp: [bootstrapper1, ion.process.bootstrap.bootstrapper, Bootstrapper]
    config:
      bootstrap_plugins:
        - plugin: [ion.process.bootstrap.plugins.bootstrap_core, BootstrapCore]

  - name: event_persister
    processapp: [event_persister, ion.process.event.event_persister, EventPersister]

  - name: resource_registry
    processapp: [resource_registry, ion.service.resource_registry_service, ResourceRegistryService]
    replicas: 1

  - name: system_management
    processapp: [system_management, ion.service.system_management_service, SystemManagementService]

  - name: directory
    processapp: [directory, ion.service.directory_service, DirectoryService]

  - name: identity_management
    processapp: [identity_management, ion.service.identity_management_service, IdentityManagementService]

  - name: policy_management
    processapp: [policy_management, ion.service.policy_management_service, PolicyManagementService]

  - name: exchange_management
    processapp: [exchange_management, ion.service.exchange_management_service, ExchangeManagementService]

  - name: org_management
    processapp: [org_management, ion.service.org_management_service, OrgManagementService]

  - name: bootstrapper2
    processapp: [bootstrapper2, ion.process.bootstrap.bootstrapper, Bootstrapper]
    config:
      bootstrap_plugins:
        - plugin: [ion.process.bootstrap.plugins.bootstrap_org, BootstrapOrg]
        - plugin: [ion.process.bootstrap.plugins.bootstrap_exchange, BootstrapExchange]

  ##################################
  # HIGHER LEVEL SERVICES
  ##################################

  - name: resource_management
    processapp: [resource_management, ion.service.resource_management_service, ResourceManagementService]

  - name: policy_bootstrap
    processapp: [policy_bootstrap, ion.process.bootstrap.bootstrapper, Bootstrapper]
    config:
      bootstrap_plugins:
        - plugin: [ion.process.bootstrap.plugins.bootstrap_policy, BootstrapPolicy]

  ##################################
  # APPLICATION SERVICES
  ##################################

  - name: scion_management
    processapp: [scion_management, scion.service.scion_management, ScionManagementService]

  ##################################
  # DEMO DATA PRELOAD
  ##################################

  - name: bootstrapper_app
    processapp: [bootstrapper_app, ion.process.bootstrap.bootstrapper, Bootstrapper]
    config:
      bootstrap_plugins:
        - plugin: [scion.process.bootstrap.boot_preload, BootstrapPreload]
        - plugin: [scion.process.bootstrap.boot_startagents, BootstrapStartAgents]

  ##################################
  # DATA INGESTION
  ##################################

  - name: ingestion_process
    processapp: [ingestion_process, ion.process.data.ingest.ingestion_process, IngestionProcess]

  - name: ingestion_process2
    processapp: [ingestion_process2, ion.process.data.ingest.ingestion_process, IngestionProcess]
    config:
      process:
        ingestion_process:
          ingestion_profile: ing2

  ##################################
  # UI SERVER WITH SERVICE GATEWAY
  ##################################

  - name: ui_server
    processapp: [ui_server, ion.process.ui.server, UIServer]
