# Minimal configuration file for bootstrapping the ION container,
# system and services via the directory.
# Note: override with pyon.local.yml and pycc command line args
system:
  root_org: ION

bootstrap:
  auto_store_interfaces: True

server:
  couchdb:
    # The basic CouchDB connection
    type: couchdb
    host: localhost
    port: 5984
    username:
    password:
  postgresql:
    type: postgresql
    host: localhost
    port: 5432
    username: ion
    password:
    admin_username:             # If empty, defaults to current login username
    admin_password:
    default_database: postgres  # Postgres' internal database
    database: ion               # Database name for OOI Network (will be sysname prefixed)

# Config values to allow discovery of the directory
container:
  profile: development

  datastore:
    default_server: postgresql  # Which server connection (and type) to use as primary datastore
    server_types:               # Definition of the known server types and how to start them
      postgresql:
        base: pyon.datastore.postgresql.base_store.PostgresDataStore
        full: pyon.datastore.postgresql.datastore.PostgresPyonDataStore
