# Resource Lifecycle related Definitions

# List of resource types (by name) for which lifecycle concepts are applied
# References names from below LifecycleWorkflowDefinitions
LifecycleResourceTypes:
  TestInstrument: ResourceLCSM
  TestPlatform: ResourceLCSM

  TestSite: SimplifiedLCSM

  TestDataset: InformationResourceLCSM

# Definition of lifecycle workflows and specializations
LifecycleWorkflowDefinitions:

  # The standard workflow with all states and transitions
  - name: ResourceLCSM
    lcsm_class: pyon.ion.resource.ResourceLifeCycleSM
    initial_lcstate: DRAFT
    initial_availability: PRIVATE
    lcstate_states: [DRAFT, PLANNED, DEVELOPED, INTEGRATED, DEPLOYED, RETIRED, DELETED]
    lcstate_transitions:
    - [DRAFT, plan, PLANNED]               # Transition: plan
    - [DRAFT, develop, DEVELOPED]          # Transition: develop
    - [PLANNED, develop, DEVELOPED]
    - [INTEGRATED, develop, DEVELOPED]
    - [DEPLOYED, develop, DEVELOPED]
    - [DRAFT, integrate, INTEGRATED]       # Transition: integrate
    - [PLANNED, integrate, INTEGRATED]
    - [DEVELOPED, integrate, INTEGRATED]
    - [DEPLOYED, integrate, INTEGRATED]
    - [DRAFT, deploy, DEPLOYED]            # Transition: deploy
    - [PLANNED, deploy, DEPLOYED]
    - [DEVELOPED, deploy, DEPLOYED]
    - [INTEGRATED, deploy, DEPLOYED]
    - [DRAFT, retire, RETIRED]             # Transition: retire
    - [PLANNED, retire, RETIRED]
    - [DEVELOPED, retire, RETIRED]
    - [INTEGRATED, retire, RETIRED]
    - [DEPLOYED, retire, RETIRED]
    - [DRAFT, delete, DELETED]             # Transition: delete
    - [PLANNED, delete, DELETED]
    - [DEVELOPED, delete, DELETED]
    - [INTEGRATED, delete, DELETED]
    - [DEPLOYED, delete, DELETED]
    - [RETIRED, delete, DELETED]
    availability_states: [PRIVATE, DISCOVERABLE, AVAILABLE]
    availability_transitions:
    - [PRIVATE, announce, DISCOVERABLE]
    - [DISCOVERABLE, unannounce, PRIVATE]
    - [AVAILABLE, unannounce, PRIVATE]
    - [PRIVATE, enable, AVAILABLE]
    - [DISCOVERABLE, enable, AVAILABLE]
    - [AVAILABLE, disable, DISCOVERABLE]

  # A simplified workflow that does not use DRAFT, DEVELOPED and starts in PLANNED_AVAILABLE
  - name: SimplifiedLCSM
    based_on: ResourceLCSM
    initial_lcstate: PLANNED
    initial_availability: AVAILABLE
    remove_states: [DRAFT, DEVELOPED]

  # A simplified workflow that does not use DRAFT, DEVELOPED, INTEGRATED and starts in PLANNED/AVAILABLE state
  - name: InformationResourceLCSM
    based_on: ResourceLCSM
    initial_lcstate: PLANNED
    initial_availability: AVAILABLE
    remove_states: [DRAFT, DEVELOPED, INTEGRATED]
